# Generated by Django 3.1 on 2021-01-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201231_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='notes',
            field=models.CharField(max_length=76),
        ),
    ]
